r=float(input("Nhap vao ban kinh cua duong tron: "))
print("Dien tich cua duong tron co ban kinh",int(r),end="")
print(" la =",round(3.14*r*r,1))
print("Chu vi cua duong tron co ban kinh" ,int(r),end="")
print(" la =",round(2*r*3.14,1))
